# Generated by Django 5.2 on 2025-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default='', help_text='Image preview of the project', upload_to='portfolio/images/'),
            preserve_default=False,
        ),
    ]
