# Generated by Django 5.2 on 2025-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Image preview of the project', null=True, upload_to='portfolio/images/'),
        ),
    ]
