# Generated by Django 5.2 on 2025-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g., CEO of Helpful Engineering', max_length=100)),
                ('image', models.ImageField(help_text='Image of the person giving the testimonial', upload_to='testimonials/images/')),
                ('quote', models.TextField(blank=True, help_text='Optional testimonial quote')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
